import type { Knex } from "knex";

// ---------------------------------------------------------------------------
// Film formats
// ---------------------------------------------------------------------------
const FILM_FORMATS: { id: string; form_factor: string; format: string }[] = [
  { id: "35mm", form_factor: "Roll", format: "35mm" },
  { id: "110", form_factor: "Roll", format: "110" },
  { id: "120", form_factor: "Roll", format: "120" },
  { id: "220", form_factor: "Roll", format: "220" },
  { id: "4x5", form_factor: "Sheet", format: "4x5" },
  { id: "8x10", form_factor: "Sheet", format: "8x10" },
  { id: "mini", form_factor: "Instant", format: "Mini" },
  { id: "wide", form_factor: "Instant", format: "Wide" },
  { id: "square", form_factor: "Instant", format: "Square" },
  { id: "i-type", form_factor: "Instant", format: "I-Type" },
  { id: "600", form_factor: "Instant", format: "600" },
  { id: "sx-70", form_factor: "Instant", format: "SX-70" },
  { id: "go", form_factor: "Instant", format: "GO" },
];

// ---------------------------------------------------------------------------
// Tags  (is_system = true tags are always synced to main tables)
// ---------------------------------------------------------------------------
const TAGS: {
  id: string;
  value: string;
  color: string;
  is_roll_scoped: boolean;
  is_stock_scoped: boolean;
  is_system: boolean;
}[] = [
  // Convenience tags
  {
    id: "color",
    value: "color",
    color: "#F97316",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "portrait",
    value: "portrait",
    color: "#EC4899",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "daylight",
    value: "daylight",
    color: "#EAB308",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "professional",
    value: "professional",
    color: "#6366F1",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "consumer",
    value: "consumer",
    color: "#10B981",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "black-white",
    value: "black-white",
    color: "#6B7280",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "street",
    value: "street",
    color: "#374151",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "classic",
    value: "classic",
    color: "#92400E",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "high-contrast",
    value: "high-contrast",
    color: "#111827",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "fine-grain",
    value: "fine-grain",
    color: "#059669",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "landscape",
    value: "landscape",
    color: "#22C55E",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "slide",
    value: "slide",
    color: "#3B82F6",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "transparency",
    value: "transparency",
    color: "#93C5FD",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "instant",
    value: "instant",
    color: "#A855F7",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "square",
    value: "square",
    color: "#F472B6",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "mini",
    value: "mini",
    color: "#FB7185",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "large-format",
    value: "large-format",
    color: "#0EA5E9",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "experimental",
    value: "experimental",
    color: "#F43F5E",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "affordable",
    value: "affordable",
    color: "#84CC16",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "high-speed",
    value: "high-speed",
    color: "#EF4444",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "t-grain",
    value: "t-grain",
    color: "#78716C",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "chromogenic",
    value: "chromogenic",
    color: "#8B5CF6",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "c41-process",
    value: "c41-process",
    color: "#D97706",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "ultra-fine-grain",
    value: "ultra-fine-grain",
    color: "#34D399",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "slow-speed",
    value: "slow-speed",
    color: "#FDE68A",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "cinema",
    value: "cinema",
    color: "#DC2626",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "motion-picture",
    value: "motion-picture",
    color: "#B91C1C",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "tungsten",
    value: "tungsten",
    color: "#F59E0B",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "low-light",
    value: "low-light",
    color: "#1E293B",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "budget",
    value: "budget",
    color: "#A3E635",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "versatile",
    value: "versatile",
    color: "#06B6D4",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "chinese",
    value: "chinese",
    color: "#EF4444",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "czech",
    value: "czech",
    color: "#1D4ED8",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "modified",
    value: "modified",
    color: "#7C3AED",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "halation",
    value: "halation",
    color: "#FCA5A5",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  {
    id: "double-x",
    value: "double-x",
    color: "#D97706",
    is_roll_scoped: true,
    is_stock_scoped: true,
    is_system: false,
  },
  // System tags — always synced to main tables, cannot be deleted
  {
    id: "expired",
    value: "expired",
    color: "#9CA3AF",
    is_roll_scoped: true,
    is_stock_scoped: false,
    is_system: true,
  },
  {
    id: "pushed",
    value: "pushed",
    color: "#A78BFA",
    is_roll_scoped: true,
    is_stock_scoped: false,
    is_system: true,
  },
  {
    id: "pulled",
    value: "pulled",
    color: "#5EEAD4",
    is_roll_scoped: true,
    is_stock_scoped: false,
    is_system: true,
  },
  {
    id: "cross-processed",
    value: "cross-processed",
    color: "#FB923C",
    is_roll_scoped: true,
    is_stock_scoped: false,
    is_system: true,
  },
];

// ---------------------------------------------------------------------------
// Stocks
// ---------------------------------------------------------------------------
const STOCKS: {
  id: string;
  format_key: string;
  process: string;
  manufacturer: string;
  brand: string;
  speed: number;
  box_image_url: string;
}[] = [
  {
    id: "kodak-portra-400-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Kodak",
    brand: "Portra 400",
    speed: 400,
    box_image_url: "https://example.com/images/kodak-portra-400.jpg",
  },
  {
    id: "fuji-superia-400-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Fujifilm",
    brand: "Superia 400",
    speed: 400,
    box_image_url: "https://example.com/images/fuji-superia-400.jpg",
  },
  {
    id: "kodak-tri-x-400-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Kodak",
    brand: "Tri-X 400",
    speed: 400,
    box_image_url: "https://example.com/images/kodak-tri-x-400.jpg",
  },
  {
    id: "kodak-ektar-100-120",
    format_key: "120",
    process: "C-41",
    manufacturer: "Kodak",
    brand: "Ektar 100",
    speed: 100,
    box_image_url: "https://example.com/images/kodak-ektar-100.jpg",
  },
  {
    id: "fuji-provia-100f-120",
    format_key: "120",
    process: "E-6",
    manufacturer: "Fujifilm",
    brand: "Provia 100F",
    speed: 100,
    box_image_url: "https://example.com/images/fuji-provia-100f.jpg",
  },
  {
    id: "polaroid-i-type-color",
    format_key: "i-type",
    process: "Instant",
    manufacturer: "Polaroid",
    brand: "i-Type Color",
    speed: 640,
    box_image_url: "https://example.com/images/polaroid-i-type-color.jpg",
  },
  {
    id: "fuji-instax-mini-color",
    format_key: "mini",
    process: "Instant",
    manufacturer: "Fujifilm",
    brand: "Instax Mini",
    speed: 800,
    box_image_url: "https://example.com/images/fuji-instax-mini.jpg",
  },
  {
    id: "kodak-portra-160-4x5",
    format_key: "4x5",
    process: "C-41",
    manufacturer: "Kodak",
    brand: "Portra 160",
    speed: 160,
    box_image_url: "https://example.com/images/kodak-portra-160-4x5.jpg",
  },
  {
    id: "harman-phoenix-200-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Harman",
    brand: "Phoenix 200",
    speed: 200,
    box_image_url: "https://example.com/images/harman-phoenix-200.jpg",
  },
  {
    id: "ilford-hp5-plus-400-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Ilford",
    brand: "HP5 Plus 400",
    speed: 400,
    box_image_url: "https://example.com/images/ilford-hp5-plus.jpg",
  },
  {
    id: "ilford-hp5-plus-400-120",
    format_key: "120",
    process: "Black & White",
    manufacturer: "Ilford",
    brand: "HP5 Plus 400",
    speed: 400,
    box_image_url: "https://example.com/images/ilford-hp5-plus-120.jpg",
  },
  {
    id: "ilford-fp4-plus-125-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Ilford",
    brand: "FP4 Plus 125",
    speed: 125,
    box_image_url: "https://example.com/images/ilford-fp4-plus.jpg",
  },
  {
    id: "ilford-delta-400-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Ilford",
    brand: "Delta 400",
    speed: 400,
    box_image_url: "https://example.com/images/ilford-delta-400.jpg",
  },
  {
    id: "ilford-xp2-super-400-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Ilford",
    brand: "XP2 Super 400",
    speed: 400,
    box_image_url: "https://example.com/images/ilford-xp2-super.jpg",
  },
  {
    id: "ilford-pan-f-plus-50-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Ilford",
    brand: "Pan F Plus 50",
    speed: 50,
    box_image_url: "https://example.com/images/ilford-pan-f-plus.jpg",
  },
  {
    id: "kodak-eastman-vision3-50d-35mm",
    format_key: "35mm",
    process: "ECN-2",
    manufacturer: "Eastman Kodak",
    brand: "Vision3 50D",
    speed: 50,
    box_image_url: "https://example.com/images/kodak-vision3-50d.jpg",
  },
  {
    id: "kodak-eastman-vision3-200t-35mm",
    format_key: "35mm",
    process: "ECN-2",
    manufacturer: "Eastman Kodak",
    brand: "Vision3 200T",
    speed: 200,
    box_image_url: "https://example.com/images/kodak-vision3-200t.jpg",
  },
  {
    id: "kodak-eastman-vision3-500t-35mm",
    format_key: "35mm",
    process: "ECN-2",
    manufacturer: "Eastman Kodak",
    brand: "Vision3 500T",
    speed: 500,
    box_image_url: "https://example.com/images/kodak-vision3-500t.jpg",
  },
  {
    id: "kodak-alaris-gold-200-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Kodak Alaris",
    brand: "Gold 200",
    speed: 200,
    box_image_url: "https://example.com/images/kodak-gold-200.jpg",
  },
  {
    id: "kodak-alaris-colorplus-200-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Kodak Alaris",
    brand: "ColorPlus 200",
    speed: 200,
    box_image_url: "https://example.com/images/kodak-colorplus-200.jpg",
  },
  {
    id: "kodak-alaris-ultramax-400-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Kodak Alaris",
    brand: "UltraMax 400",
    speed: 400,
    box_image_url: "https://example.com/images/kodak-ultramax-400.jpg",
  },
  {
    id: "lucky-shd-100-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Lucky",
    brand: "SHD 100",
    speed: 100,
    box_image_url: "https://example.com/images/lucky-shd-100.jpg",
  },
  {
    id: "lucky-shd-100-120",
    format_key: "120",
    process: "Black & White",
    manufacturer: "Lucky",
    brand: "SHD 100",
    speed: 100,
    box_image_url: "https://example.com/images/lucky-shd-100-120.jpg",
  },
  {
    id: "lucky-color-100-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "Lucky",
    brand: "Lucky Color 100",
    speed: 100,
    box_image_url: "https://example.com/images/lucky-color-100.jpg",
  },
  {
    id: "fomapan-100-classic-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Foma",
    brand: "Fomapan 100 Classic",
    speed: 100,
    box_image_url: "https://example.com/images/fomapan-100-classic.jpg",
  },
  {
    id: "fomapan-100-classic-120",
    format_key: "120",
    process: "Black & White",
    manufacturer: "Foma",
    brand: "Fomapan 100 Classic",
    speed: 100,
    box_image_url: "https://example.com/images/fomapan-100-classic-120.jpg",
  },
  {
    id: "fomapan-200-creative-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Foma",
    brand: "Fomapan 200 Creative",
    speed: 200,
    box_image_url: "https://example.com/images/fomapan-200-creative.jpg",
  },
  {
    id: "fomapan-400-action-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "Foma",
    brand: "Fomapan 400 Action",
    speed: 400,
    box_image_url: "https://example.com/images/fomapan-400-action.jpg",
  },
  {
    id: "fomapan-100-classic-4x5",
    format_key: "4x5",
    process: "Black & White",
    manufacturer: "Foma",
    brand: "Fomapan 100 Classic",
    speed: 100,
    box_image_url: "https://example.com/images/fomapan-100-classic-4x5.jpg",
  },
  {
    id: "cinestill-50d-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "CineStill",
    brand: "50D",
    speed: 50,
    box_image_url: "https://example.com/images/cinestill-50d.jpg",
  },
  {
    id: "cinestill-800t-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "CineStill",
    brand: "800T",
    speed: 800,
    box_image_url: "https://example.com/images/cinestill-800t.jpg",
  },
  {
    id: "cinestill-800t-120",
    format_key: "120",
    process: "C-41",
    manufacturer: "CineStill",
    brand: "800T",
    speed: 800,
    box_image_url: "https://example.com/images/cinestill-800t-120.jpg",
  },
  {
    id: "cinestill-400d-35mm",
    format_key: "35mm",
    process: "C-41",
    manufacturer: "CineStill",
    brand: "400D",
    speed: 400,
    box_image_url: "https://example.com/images/cinestill-400d.jpg",
  },
  {
    id: "cinestill-bwxx-35mm",
    format_key: "35mm",
    process: "Black & White",
    manufacturer: "CineStill",
    brand: "BwXX",
    speed: 250,
    box_image_url: "https://example.com/images/cinestill-bwxx.jpg",
  },
];

// ---------------------------------------------------------------------------
// Stock tags
// ---------------------------------------------------------------------------
const STOCK_TAGS: { stock_key: string; tag_key: string }[] = [
  { stock_key: "kodak-portra-400-35mm", tag_key: "color" },
  { stock_key: "kodak-portra-400-35mm", tag_key: "portrait" },
  { stock_key: "kodak-portra-400-35mm", tag_key: "daylight" },
  { stock_key: "kodak-portra-400-35mm", tag_key: "professional" },
  { stock_key: "fuji-superia-400-35mm", tag_key: "color" },
  { stock_key: "fuji-superia-400-35mm", tag_key: "consumer" },
  { stock_key: "fuji-superia-400-35mm", tag_key: "daylight" },
  { stock_key: "kodak-tri-x-400-35mm", tag_key: "black-white" },
  { stock_key: "kodak-tri-x-400-35mm", tag_key: "street" },
  { stock_key: "kodak-tri-x-400-35mm", tag_key: "classic" },
  { stock_key: "kodak-tri-x-400-35mm", tag_key: "high-contrast" },
  { stock_key: "kodak-ektar-100-120", tag_key: "color" },
  { stock_key: "kodak-ektar-100-120", tag_key: "fine-grain" },
  { stock_key: "kodak-ektar-100-120", tag_key: "landscape" },
  { stock_key: "kodak-ektar-100-120", tag_key: "professional" },
  { stock_key: "fuji-provia-100f-120", tag_key: "slide" },
  { stock_key: "fuji-provia-100f-120", tag_key: "transparency" },
  { stock_key: "fuji-provia-100f-120", tag_key: "fine-grain" },
  { stock_key: "fuji-provia-100f-120", tag_key: "professional" },
  { stock_key: "polaroid-i-type-color", tag_key: "instant" },
  { stock_key: "polaroid-i-type-color", tag_key: "color" },
  { stock_key: "polaroid-i-type-color", tag_key: "square" },
  { stock_key: "fuji-instax-mini-color", tag_key: "instant" },
  { stock_key: "fuji-instax-mini-color", tag_key: "color" },
  { stock_key: "fuji-instax-mini-color", tag_key: "mini" },
  { stock_key: "kodak-portra-160-4x5", tag_key: "color" },
  { stock_key: "kodak-portra-160-4x5", tag_key: "portrait" },
  { stock_key: "kodak-portra-160-4x5", tag_key: "large-format" },
  { stock_key: "kodak-portra-160-4x5", tag_key: "professional" },
  { stock_key: "harman-phoenix-200-35mm", tag_key: "black-white" },
  { stock_key: "harman-phoenix-200-35mm", tag_key: "experimental" },
  { stock_key: "harman-phoenix-200-35mm", tag_key: "affordable" },
  { stock_key: "ilford-hp5-plus-400-35mm", tag_key: "black-white" },
  { stock_key: "ilford-hp5-plus-400-35mm", tag_key: "classic" },
  { stock_key: "ilford-hp5-plus-400-35mm", tag_key: "high-speed" },
  { stock_key: "ilford-hp5-plus-400-35mm", tag_key: "professional" },
  { stock_key: "ilford-hp5-plus-400-120", tag_key: "black-white" },
  { stock_key: "ilford-hp5-plus-400-120", tag_key: "classic" },
  { stock_key: "ilford-hp5-plus-400-120", tag_key: "high-speed" },
  { stock_key: "ilford-hp5-plus-400-120", tag_key: "professional" },
  { stock_key: "ilford-fp4-plus-125-35mm", tag_key: "black-white" },
  { stock_key: "ilford-fp4-plus-125-35mm", tag_key: "fine-grain" },
  { stock_key: "ilford-fp4-plus-125-35mm", tag_key: "portrait" },
  { stock_key: "ilford-fp4-plus-125-35mm", tag_key: "professional" },
  { stock_key: "ilford-delta-400-35mm", tag_key: "black-white" },
  { stock_key: "ilford-delta-400-35mm", tag_key: "t-grain" },
  { stock_key: "ilford-delta-400-35mm", tag_key: "professional" },
  { stock_key: "ilford-delta-400-35mm", tag_key: "fine-grain" },
  { stock_key: "ilford-xp2-super-400-35mm", tag_key: "chromogenic" },
  { stock_key: "ilford-xp2-super-400-35mm", tag_key: "black-white" },
  { stock_key: "ilford-xp2-super-400-35mm", tag_key: "c41-process" },
  { stock_key: "ilford-pan-f-plus-50-35mm", tag_key: "black-white" },
  { stock_key: "ilford-pan-f-plus-50-35mm", tag_key: "ultra-fine-grain" },
  { stock_key: "ilford-pan-f-plus-50-35mm", tag_key: "slow-speed" },
  { stock_key: "ilford-pan-f-plus-50-35mm", tag_key: "professional" },
  { stock_key: "kodak-eastman-vision3-50d-35mm", tag_key: "cinema" },
  { stock_key: "kodak-eastman-vision3-50d-35mm", tag_key: "motion-picture" },
  { stock_key: "kodak-eastman-vision3-50d-35mm", tag_key: "daylight" },
  { stock_key: "kodak-eastman-vision3-50d-35mm", tag_key: "professional" },
  { stock_key: "kodak-eastman-vision3-200t-35mm", tag_key: "cinema" },
  { stock_key: "kodak-eastman-vision3-200t-35mm", tag_key: "motion-picture" },
  { stock_key: "kodak-eastman-vision3-200t-35mm", tag_key: "tungsten" },
  { stock_key: "kodak-eastman-vision3-200t-35mm", tag_key: "professional" },
  { stock_key: "kodak-eastman-vision3-500t-35mm", tag_key: "cinema" },
  { stock_key: "kodak-eastman-vision3-500t-35mm", tag_key: "motion-picture" },
  { stock_key: "kodak-eastman-vision3-500t-35mm", tag_key: "tungsten" },
  { stock_key: "kodak-eastman-vision3-500t-35mm", tag_key: "low-light" },
  { stock_key: "kodak-alaris-gold-200-35mm", tag_key: "color" },
  { stock_key: "kodak-alaris-gold-200-35mm", tag_key: "consumer" },
  { stock_key: "kodak-alaris-gold-200-35mm", tag_key: "affordable" },
  { stock_key: "kodak-alaris-gold-200-35mm", tag_key: "daylight" },
  { stock_key: "kodak-alaris-colorplus-200-35mm", tag_key: "color" },
  { stock_key: "kodak-alaris-colorplus-200-35mm", tag_key: "consumer" },
  { stock_key: "kodak-alaris-colorplus-200-35mm", tag_key: "budget" },
  { stock_key: "kodak-alaris-colorplus-200-35mm", tag_key: "daylight" },
  { stock_key: "kodak-alaris-ultramax-400-35mm", tag_key: "color" },
  { stock_key: "kodak-alaris-ultramax-400-35mm", tag_key: "consumer" },
  { stock_key: "kodak-alaris-ultramax-400-35mm", tag_key: "versatile" },
  { stock_key: "kodak-alaris-ultramax-400-35mm", tag_key: "affordable" },
  { stock_key: "lucky-shd-100-35mm", tag_key: "black-white" },
  { stock_key: "lucky-shd-100-35mm", tag_key: "chinese" },
  { stock_key: "lucky-shd-100-35mm", tag_key: "affordable" },
  { stock_key: "lucky-shd-100-35mm", tag_key: "fine-grain" },
  { stock_key: "lucky-shd-100-120", tag_key: "black-white" },
  { stock_key: "lucky-shd-100-120", tag_key: "chinese" },
  { stock_key: "lucky-shd-100-120", tag_key: "affordable" },
  { stock_key: "lucky-shd-100-120", tag_key: "fine-grain" },
  { stock_key: "lucky-color-100-35mm", tag_key: "color" },
  { stock_key: "lucky-color-100-35mm", tag_key: "chinese" },
  { stock_key: "lucky-color-100-35mm", tag_key: "affordable" },
  { stock_key: "lucky-color-100-35mm", tag_key: "daylight" },
  { stock_key: "fomapan-100-classic-35mm", tag_key: "black-white" },
  { stock_key: "fomapan-100-classic-35mm", tag_key: "czech" },
  { stock_key: "fomapan-100-classic-35mm", tag_key: "affordable" },
  { stock_key: "fomapan-100-classic-35mm", tag_key: "fine-grain" },
  { stock_key: "fomapan-100-classic-120", tag_key: "black-white" },
  { stock_key: "fomapan-100-classic-120", tag_key: "czech" },
  { stock_key: "fomapan-100-classic-120", tag_key: "affordable" },
  { stock_key: "fomapan-100-classic-120", tag_key: "fine-grain" },
  { stock_key: "fomapan-200-creative-35mm", tag_key: "black-white" },
  { stock_key: "fomapan-200-creative-35mm", tag_key: "czech" },
  { stock_key: "fomapan-200-creative-35mm", tag_key: "affordable" },
  { stock_key: "fomapan-200-creative-35mm", tag_key: "versatile" },
  { stock_key: "fomapan-400-action-35mm", tag_key: "black-white" },
  { stock_key: "fomapan-400-action-35mm", tag_key: "czech" },
  { stock_key: "fomapan-400-action-35mm", tag_key: "affordable" },
  { stock_key: "fomapan-400-action-35mm", tag_key: "high-speed" },
  { stock_key: "fomapan-100-classic-4x5", tag_key: "black-white" },
  { stock_key: "fomapan-100-classic-4x5", tag_key: "czech" },
  { stock_key: "fomapan-100-classic-4x5", tag_key: "affordable" },
  { stock_key: "fomapan-100-classic-4x5", tag_key: "large-format" },
  { stock_key: "fomapan-100-classic-4x5", tag_key: "fine-grain" },
  { stock_key: "cinestill-50d-35mm", tag_key: "color" },
  { stock_key: "cinestill-50d-35mm", tag_key: "cinema" },
  { stock_key: "cinestill-50d-35mm", tag_key: "daylight" },
  { stock_key: "cinestill-50d-35mm", tag_key: "fine-grain" },
  { stock_key: "cinestill-50d-35mm", tag_key: "modified" },
  { stock_key: "cinestill-800t-35mm", tag_key: "color" },
  { stock_key: "cinestill-800t-35mm", tag_key: "cinema" },
  { stock_key: "cinestill-800t-35mm", tag_key: "tungsten" },
  { stock_key: "cinestill-800t-35mm", tag_key: "high-speed" },
  { stock_key: "cinestill-800t-35mm", tag_key: "halation" },
  { stock_key: "cinestill-800t-35mm", tag_key: "modified" },
  { stock_key: "cinestill-800t-120", tag_key: "color" },
  { stock_key: "cinestill-800t-120", tag_key: "cinema" },
  { stock_key: "cinestill-800t-120", tag_key: "tungsten" },
  { stock_key: "cinestill-800t-120", tag_key: "high-speed" },
  { stock_key: "cinestill-800t-120", tag_key: "halation" },
  { stock_key: "cinestill-800t-120", tag_key: "modified" },
  { stock_key: "cinestill-400d-35mm", tag_key: "color" },
  { stock_key: "cinestill-400d-35mm", tag_key: "cinema" },
  { stock_key: "cinestill-400d-35mm", tag_key: "daylight" },
  { stock_key: "cinestill-400d-35mm", tag_key: "versatile" },
  { stock_key: "cinestill-400d-35mm", tag_key: "modified" },
  { stock_key: "cinestill-bwxx-35mm", tag_key: "black-white" },
  { stock_key: "cinestill-bwxx-35mm", tag_key: "cinema" },
  { stock_key: "cinestill-bwxx-35mm", tag_key: "double-x" },
  { stock_key: "cinestill-bwxx-35mm", tag_key: "modified" },
  { stock_key: "cinestill-bwxx-35mm", tag_key: "high-contrast" },
];

export async function up(knex: Knex): Promise<void> {
  const now = knex.fn.now();

  await knex("film_formats_default")
    .insert(FILM_FORMATS.map((r) => ({ ...r, created_at: now })))
    .onConflict("id")
    .ignore();

  await knex("tags_default")
    .insert(TAGS.map((r) => ({ ...r, created_at: now })))
    .onConflict("id")
    .ignore();

  await knex("stocks_default")
    .insert(STOCKS.map((r) => ({ ...r, created_at: now })))
    .onConflict("id")
    .ignore();

  // stock_tags have no meaningful natural key — conflict on the unique pair
  await knex.raw(
    `INSERT INTO stock_tags_default (id, stock_key, tag_key, created_at)
     SELECT gen_random_uuid(), v.stock_key, v.tag_key, NOW()
     FROM (VALUES ${STOCK_TAGS.map(() => "(?, ?)").join(", ")}) AS v(stock_key, tag_key)
     ON CONFLICT (stock_key, tag_key) DO NOTHING`,
    STOCK_TAGS.flatMap((r) => [r.stock_key, r.tag_key]),
  );
}

export async function down(knex: Knex): Promise<void> {
  await knex("stock_tags_default").delete();
  await knex("stocks_default").delete();
  await knex("tags_default").delete();
  await knex("film_formats_default").delete();
}
